development:
  dialect: postgres
  database: shrt_development
  user: klauer
  password: klauer
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://klauer:klauerj@127.0.0.1:5432/shrt_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://klauer:klauer@127.0.0.1:5432/shrt_production?sslmode=disable"}}